version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Puerto AMQP
      - "15672:15672"    # Dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: weather_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  rabbitmq_data:
  postgres_data:
